index:
    path: /
    methods: GET
    controller: App\Controller\PizzaController::index

add_pizza:
    path: pizza/add
    methods: POST
    controller: App\Controller\PizzaController::addPizza

show_pizza:
    path: pizza/{pizzaID}
    methods: GET
    controller: App\Controller\PizzaController::viewPizza

delete_pizza:
    path: /pizza/{pizzaId}/delete
    methods: POST
    controller: App\Controller\PizzaController::deletePizza